openapi: 3.2.0
info:
  contact:
    email: partner-api@wish.com
  x-wish-dev-contact:
    assignee: kwei
    email: marketplace-external-api@contextlogic.com
  description: 'Wish Marketplace V3 API


    # General Information


    The Wish Marketplace API will be using oAuth to authenticate in order to offer better security for its users


    * Learn about oAuth here.'
  version: 3.0.65
  title: Wish Marketplace V3 France EPR Compliance API
servers:
- url: https://merchant.wish.com
  description: V3 API endpoint
security:
- OAuth2: []
tags:
- description: 'APIs that support France Extended Producer Responsibility (EPR) Compliance.

    For a merchant to be compliant with the EPR regulation, a product category they intend to sell must be linked with one or more EPR registration number(s).'
  name: France EPR Compliance
paths:
  /api/v3/france_epr_compliance/compliance_status:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FranceProductComplianceStatusResponse'
          description: successfully updated france product compliance status for input products
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to update for france product compliance status for input products
      tags:
      - France EPR Compliance
      summary: Bulk update France EPR Product Compliance Status
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/FranceProductComplianceStatusRequest'
              type: array
              description: List of product ids associated with update request on France EPR Product Compliance Status
              maxItems: 500
      security:
      - OAuth2:
        - compliance:write
      operationId: updateFranceEPRProductComplianceStatus
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"[{\\\"product_id\\\":\\\"string\\\",\\\"unique_identification_number_id\\\":\\\"string\\\"}]\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"[{\\\"product_id\\\":\\\"string\\\",\\\"unique_identification_number_id\\\":\\\"string\\\"}]\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"[{\\\"product_id\\\":\\\"string\\\",\\\"unique_identification_number_id\\\":\\\"string\\\"}]\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '[{\"product_id\":\"string\",\"unique_identification_number_id\":\"string\"}]'"
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status\"\n\npayload = \"[{\\\"product_id\\\":\\\"string\\\",\\\"unique_identification_number_id\\\":\\\"string\\\"}]\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      description: 'Update the France Extended Producer Responsibility compliance status for each input product by linking with the associated input uin_id or unlinking the existing UIN if the associated input uin_id is empty or null.

        The input array size limitation is 500.'
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FranceProductComplianceStatusResponse'
          description: successfully queried for product compliance status
        '400':
          content:
            application/json:
              examples:
                ExtAPIUniqueIdentificationNumberNotFoundException:
                  value:
                    message: The input france product unique identification number is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for product compliance status
      parameters:
      - in: query
        description: The list of the product IDs that will be returned with the compliance status
        name: product_ids
        schema:
          items:
            type: string
            description: The unique identifiers of a product
            format: object-id
          type: array
          maxItems: 500
      - required: false
        in: query
        description: The beginning product id(inclusive) of the result array. If not provided, will use the smallest product id.</br> Ignored when `product_ids` is provided.
        name: product_id_min
        schema:
          type: string
          format: object-id
      - required: false
        in: query
        description: The ending product id(inclusive) of the result array. If not provided, will use the largest product id.</br> Ignored when `product_ids` is provided.
        name: product_id_max
        schema:
          type: string
          format: object-id
      - in: query
        description: A limit on the number of records that will be returned.</br> Ignored when `product_ids` is provided.
        name: limit
        schema:
          default: 100
          minimum: 0
          type: integer
          maximum: 500
      - in: query
        description: Sort results by the given attribute. Enabled attributes are `product_id`. Default order is `asc`, use `desc` to sort in reverse.</br> Ignored when `product_ids` is provided.
        name: sort_by
        schema:
          default: product_id.asc
          pattern: ^product_id(\.(asc|desc))?$
          type: string
      tags:
      - France EPR Compliance
      summary: Get France EPR Product Compliance Status
      security:
      - OAuth2:
        - compliance:read
      operationId: getFranceEPRProductComplianceStatus
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/france_epr_compliance/compliance_status"


          querystring = {"product_ids":"SOME_ARRAY_VALUE","product_id_min":"SOME_STRING_VALUE","product_id_max":"SOME_STRING_VALUE","limit":"SOME_INTEGER_VALUE","sort_by":"SOME_STRING_VALUE"}


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers, params=querystring)


          print(response.text)'
      description: 'Get the France Extended Producer Responsibility product compliance status and the unique identifier number ids (if linked) for each input product.

        If there is no input product id, then get the result of all products from a merchant.

        The unique identifier number id will be empty for products that are not linked with any unique identifier number.'
  /api/v3/france_epr_compliance/unique_identification_number:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FranceProductUniqueIdentificationNumberResponse'
          description: successfully created a new france product unique identification number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIUniqueIdentificationNumberInvalidFieldException:
                  value:
                    message: The input unique identification number has invalid fields.
                    code: '10001'
                ExtAPIUniqueIdentificationNumberExceedLimitException:
                  value:
                    message: The category exceeds the limit of 1 UIN per category on the operated merchant.
                    code: '10002'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to create a new new france product unique identification number.
      tags:
      - France EPR Compliance
      summary: Create a France Product Unique Identification Number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFranceProductUniqueIdentificationNumber'
      security:
      - OAuth2:
        - compliance:write
      operationId: createFranceProductUniqueIdentificationNumber
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.post(\"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"category\\\":\\\"BATTERIES\\\",\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"POST\",\n  CURLOPT_POSTFIELDS => \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\",\n  \"method\": \"POST\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request POST \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"category\":\"BATTERIES\",\"product_responsibility_organization\":\"string\",\"uin\":\"string\"}'"
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\"\n\npayload = \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"POST\", url, data=payload, headers=headers)\n\nprint(response.text)"
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFranceProductUniqueIdentificationNumbersResponse'
          description: successfully queried for France product unique identification numbers.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for France product unique identification numbers.
      tags:
      - France EPR Compliance
      description: List all France Product Identification Numbers and their product categories created by a merchant.
      summary: List France Product Unique Identification Numbers
      security:
      - OAuth2:
        - compliance:read
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      operationId: listFranceProductUniqueIdentificationNumber
  /api/v3/france_epr_compliance/unique_identification_number/{id}:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FranceProductUniqueIdentificationNumberResponse'
          description: successfully updated a france product unique identification number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIUniqueIdentificationNumberInvalidFieldException:
                  value:
                    message: The input unique identification number has invalid fields.
                    code: '10001'
                ExtAPIUniqueIdentificationNumberNotFoundException:
                  value:
                    message: The input france product unique identification number is not found by the given id.
                    code: '10003'
                ExtAPIUpdateInvalidUniqueIdentificationNumberException:
                  value:
                    message: The france product unique identification number is already rejected or deleted, so not able to update.
                    code: '10007'
                ExtAPIUniqueIdentificationNumberNoAccessException:
                  value:
                    message: The france product unique identification number is not accessable for the operated merchant.
                    code: '10004'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to update a france product unique identification number.
      parameters:
      - $ref: '#/components/parameters/uin_id'
      tags:
      - France EPR Compliance
      summary: Update a France Product Unique Identification Number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFranceProductUniqueIdentificationNumber'
      security:
      - OAuth2:
        - compliance:write
      operationId: updateFranceProductUniqueIdentificationNumber
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"{\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"product_responsibility_organization\":\"string\",\"uin\":\"string\"}'"
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\"\n\npayload = \"{\\\"product_responsibility_organization\\\":\\\"string\\\",\\\"uin\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      description: Update details of a France Product Identification Number.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FranceProductUniqueIdentificationNumberResponse'
          description: successfully queried for a france product unique identification number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIUniqueIdentificationNumberNotFoundException:
                  value:
                    message: The input france product unique identification number is not found by the given id.
                    code: '10003'
                ExtAPIUniqueIdentificationNumberNoAccessException:
                  value:
                    message: The france product unique identification number is not accessable for the operated merchant.
                    code: '10004'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for a france product unique identification number.
      parameters:
      - $ref: '#/components/parameters/uin_id'
      tags:
      - France EPR Compliance
      summary: Get a France Product Unique Identification Number
      security:
      - OAuth2:
        - compliance:read
      operationId: getFranceProductUniqueIdentificationNumber
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      description: Get a France Product Identification Number and its product categories given its id.
    delete:
      responses:
        '204':
          description: successfully deleted a France Product Unique Identification Number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIDeleteUniqueIdentificationNumberException:
                  value:
                    message: The unique identification number is still linked with some products, so not able to delete before unlinking to all related products.
                    code: '10006'
                ExtAPIUniqueIdentificationNumberInvalidFieldException:
                  value:
                    message: The input unique identification number has invalid fields.
                    code: '10001'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to delete a France Product Unique Identification Number.
      parameters:
      - $ref: '#/components/parameters/uin_id'
      tags:
      - France EPR Compliance
      summary: Delete a France Product Unique Identification Number
      security:
      - OAuth2:
        - compliance:write
      operationId: deleteFranceProductUniqueIdentificationNumber
      x-code-samples:
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.delete(\"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"DELETE\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}\",\n  \"method\": \"DELETE\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: shell_curl
        source: "curl --request DELETE \\\n  --url 'https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/france_epr_compliance/unique_identification_number/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("DELETE", url, headers=headers)


          print(response.text)'
      description: Delete a France Product Unique Identification Number.
components:
  schemas:
    FranceProductComplianceStatusRequest:
      required:
      - product_id
      type: object
      properties:
        unique_identification_number_id:
          type: string
          description: The unique identifier of a unique identification number that is submitted by the merchant for compliance reasons
          format: object-id
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
    FranceProductComplianceStatusResponse:
      items:
        $ref: '#/components/schemas/FranceProductComplianceStatus'
      type: array
      description: List of objects including a product id, compliance status and UIN id.
    EPRComplianceStatus:
      enum:
      - UNIQUE_IDENTIFICATION_NUMBER_LINKED
      - NO_UNIQUE_IDENTIFICATION_NUMBER
      - NOT_RECOMMENDED_TO_LINK_UNIQUE_IDENTIFICATION_NUMBER
      type: string
      description: ' 3 status: (1) a unique identification number linked, (2) no unique identification number, (3) not recommended to link a unique identification number.'
    FranceProductComplianceStatus:
      type: object
      properties:
        unique_identification_number_ids:
          items:
            type: string
            description: The unique identifiers of a product
            format: object-id
          type: array
          description: List of unique identifier of unique identification numbers that are submitted by the merchant for compliance reasons
          maxItems: 500
        compliance_status:
          $ref: '#/components/schemas/EPRComplianceStatus'
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
    FranceProductUniqueIdentificationNumberResponse:
      description: a france product unique identification number response
      allOf:
      - $ref: '#/components/schemas/FranceProductUniqueIdentificationNumber'
      - type: object
        properties:
          id:
            type: string
            description: The unique identifier of a france product unique identification number
            format: object-id
    APIError:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
    CreateFranceProductUniqueIdentificationNumber:
      type: object
      description: details of creating a france product unique identification number
      allOf:
      - $ref: '#/components/schemas/FranceProductUniqueIdentificationNumber'
      - required:
        - category
        - uin
        - product_responsibility_organization
        type: object
    UpdateFranceProductUniqueIdentificationNumber:
      type: object
      description: details of updating a france product unique identification number
      properties:
        uin:
          minLength: 1
          type: string
          description: The unique identification number(UIN) provided by the merchant
        product_responsibility_organization:
          type: string
          description: The name of the UIN provided by the merchant
    FranceProductUniqueIdentificationNumber:
      type: object
      description: details of a france product unique identification number
      properties:
        category:
          enum:
          - BATTERIES
          - ELECTRIC_AND_ELECTRONIC_EQUIPMENTS
          - FURNITURE
          - PAPER
          - TEXTILE
          - TIRES
          - PRIMARY_PACKAGING
          - SECONDARY_PACKAGING
          - TOYS
          - GARDEN_DIY
          - SPORTING_AND_RECREATIONAL
          type: string
          description: The enum representing the product category with which the UIN is associated.
        uin:
          minLength: 1
          type: string
          description: The unique identification number(UIN) provided by the merchant
        product_responsibility_organization:
          minLength: 1
          type: string
          description: The name of the UIN provided by the merchant
    ListFranceProductUniqueIdentificationNumbersResponse:
      items:
        $ref: '#/components/schemas/FranceProductUniqueIdentificationNumberResponse'
      type: array
      description: List of France Product Unique Identification Numbers returned
  parameters:
    uin_id:
      schema:
        type: string
        format: object-id
      required: true
      description: The unique identifier of the france product unique identification number
      name: id
      in: path
  securitySchemes:
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://merchant.wish.com/oidc/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            payments:write: Update payments
            tickets:write: Write customer tickets
            epc:read: read EPC info
            returns:write: Write returns
            returns:read: Read returns
            fbw:read: Read FBW
            products:read: Read products
            payments:read: Read payments
            fbw:write: Write FBW
            merchant:write: Write merchant
            products:write: Write products
            ratings:read: Read ratings
            videos:read: Read videos
            compliance:write: Write Compliance
            product_boost:read: Read ProductBoost
            listing_quality:read: Read listing quality
            webhook:write: Write webhook
            orders:read: Read orders
            compliance:read: Read Compliance
            fbs:read: Read FBS
            penalties:read: Read penalties
            penalties:write: Update penalties
            infractions:read: Read infractions
            orders:write: Update orders
            merchant:read: Read merchant
            notifications:write: Write notifications
            announcements:read: Read announcements
            product_boost:write: Write ProductBoost
            notifications:read: Read notifications
            webhook:read: Read webhook
            qoo10:read: Read Qoo10
            wps_parcel:write: Write WishParcel
            wps_parcel:read: Read WishParcel
            tickets:read: Read customer tickets
            infractions:write: Write infractions
            videos:write: Write videos
            epc:write: write EPC info
          tokenUrl: https://merchant.wish.com/api/v3/oauth/access_token
          refreshUrl: https://merchant.wish.com/api/v3/oauth/refresh_token
          authorizationUrl: https://merchant.wish.com/v3/oauth/authorize
externalDocs:
  url: https://merchant.wish.com/documentation/api/v3/explorer
  description: API explorer
x-wish-hidden: false
