openapi: 3.2.0
info:
  contact:
    email: partner-api@wish.com
  x-wish-dev-contact:
    assignee: kwei
    email: marketplace-external-api@contextlogic.com
  description: 'Wish Marketplace V3 API


    # General Information


    The Wish Marketplace API will be using oAuth to authenticate in order to offer better security for its users


    * Learn about oAuth here.'
  version: 3.0.65
  title: Wish Marketplace V3 Germany EPR Compliance API
servers:
- url: https://merchant.wish.com
  description: V3 API endpoint
security:
- OAuth2: []
tags:
- description: 'APIs that support Germany Extended Producer Responsibility (EPR) Compliance.

    For a merchant to be compliant with the EPR regulation, their applicable products must be linked with one or more EPR registration number.'
  name: Germany EPR Compliance
paths:
  /api/v3/germany_epr_compliance/epr_registration_number:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GermanyProductEprRegistrationNumberResponse'
          description: Successfully created a new Germany product EPR registration number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIEprRegistrationNumberExceedLimitException:
                  value:
                    message: The category exceeds the limit of 1 EPR number per category on the operated merchant.
                    code: '10002'
                ExtAPIEprRegistrationNumberMissingProException:
                  value:
                    message: The product responsibility organization input is mandatory for this category.
                    code: '10008'
                ExtAPIEprRegistrationNumberInvalidFieldException:
                  value:
                    message: The input EPR registration number has invalid fields.
                    code: '10001'
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to create a new Germany product EPR registration number.
      tags:
      - Germany EPR Compliance
      summary: Create a Germany Product EPR Registration Number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGermanyProductEprRegistrationNumber'
      security:
      - OAuth2:
        - compliance:write
      operationId: createGermanyProductEprRegistrationNumber
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\"\n\npayload = \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"POST\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\",\n  \"method\": \"POST\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"POST\",\n  CURLOPT_POSTFIELDS => \"{\\\"category\\\":\\\"BATTERIES\\\",\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request POST \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"category\":\"BATTERIES\",\"epr_number\":\"string\",\"organization_or_representative_name\":\"string\"}'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.post(\"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"category\\\":\\\"BATTERIES\\\",\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\")\n  .asString();"
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListGermanyProductEprRegistrationNumbersResponse'
          description: Successfully queried all Germany EPR registration numbers.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to query for Germany EPR registration numbers.
      tags:
      - Germany EPR Compliance
      description: List all Germany product EPR numbers and their product categories created by a merchant.
      summary: List Germany EPR Registration Numbers
      security:
      - OAuth2:
        - compliance:read
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      operationId: listGermanyProductEprRegistrationNumbers
  /api/v3/germany_epr_compliance/compliance_status:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GermanyProductComplianceStatusResponse'
          description: Successfully updated Germany product compliance status for input products.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to update Germany product compliance status for input products.
      tags:
      - Germany EPR Compliance
      summary: Bulk update Germany EPR Product Compliance Status
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/GermanyProductComplianceStatusRequest'
              type: array
              description: List of product ids associated with update request on Germany EPR Product Compliance Status
              maxItems: 500
      security:
      - OAuth2:
        - compliance:write
      operationId: updateGermanyEPRProductComplianceStatus
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status\"\n\npayload = \"[{\\\"epr_registration_number_id\\\":\\\"string\\\",\\\"product_id\\\":\\\"string\\\"}]\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"[{\\\"epr_registration_number_id\\\":\\\"string\\\",\\\"product_id\\\":\\\"string\\\"}]\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"[{\\\"epr_registration_number_id\\\":\\\"string\\\",\\\"product_id\\\":\\\"string\\\"}]\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '[{\"epr_registration_number_id\":\"string\",\"product_id\":\"string\"}]'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"[{\\\"epr_registration_number_id\\\":\\\"string\\\",\\\"product_id\\\":\\\"string\\\"}]\")\n  .asString();"
      description: 'Update the Germany Extended Producer Responsibility compliance status for each input product by linking with the associated input epr_id or unlinking the existing EPR number if the associated input epr_id is empty or null.

        The input array size limitation is 500.'
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GermanyProductComplianceStatusResponse'
          description: Successfully queried for product compliance status.
        '400':
          content:
            application/json:
              examples:
                ExtAPIEprRegistrationNumberNotFoundException:
                  value:
                    message: The input Germany product EPR registration number is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to query for product compliance status.
      parameters:
      - in: query
        description: The list of the product IDs that will be returned with the compliance status
        name: product_ids
        schema:
          items:
            type: string
            description: The unique identifiers of a product
            format: object-id
          type: array
          maxItems: 500
      - required: false
        in: query
        description: The beginning product id(inclusive) of the result array. If not provided, will use the smallest product id.</br> Ignored when `product_ids` is provided.
        name: product_id_min
        schema:
          type: string
          format: object-id
      - required: false
        in: query
        description: The ending product id(inclusive) of the result array. If not provided, will use the largest product id.</br> Ignored when `product_ids` is provided.
        name: product_id_max
        schema:
          type: string
          format: object-id
      - in: query
        description: A limit on the number of records that will be returned.</br> Ignored when `product_ids` is provided.
        name: limit
        schema:
          default: 100
          minimum: 0
          type: integer
          maximum: 500
      - in: query
        description: Sort results by the given attribute. Enabled attributes are `product_id`. Default order is `asc`, use `desc` to sort in reverse.</br> Ignored when `product_ids` is provided.
        name: sort_by
        schema:
          default: product_id.asc
          pattern: ^product_id(\.(asc|desc))?$
          type: string
      tags:
      - Germany EPR Compliance
      summary: Get Germany EPR Product Compliance Status
      security:
      - OAuth2:
        - compliance:read
      operationId: getGermanyEPRProductComplianceStatus
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status"


          querystring = {"product_ids":"SOME_ARRAY_VALUE","product_id_min":"SOME_STRING_VALUE","product_id_max":"SOME_STRING_VALUE","limit":"SOME_INTEGER_VALUE","sort_by":"SOME_STRING_VALUE"}


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers, params=querystring)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/germany_epr_compliance/compliance_status?product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      description: 'Get the Germany Extended Producer Responsibility product compliance status and the EPR registration number ids (if linked) for each input product.

        If there is no input product id, then get the result of all products from a merchant.

        The EPR registration id will be empty for products that are not linked with any EPR registration number.'
  /api/v3/germany_epr_compliance/epr_registration_number/{id}:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GermanyProductEprRegistrationNumberResponse'
          description: Successfully updated a Germany product EPR registration number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIEprRegistrationNumberNoAccessException:
                  value:
                    message: The Germany product EPR registration number is not accessable for the operated merchant.
                    code: '10004'
                ExtAPIEprRegistrationNumberNotFoundException:
                  value:
                    message: The input Germany product EPR registration number is not found by the given id.
                    code: '10003'
                ExtAPIEprRegistrationNumberInvalidFieldException:
                  value:
                    message: The input EPR registration number has invalid fields.
                    code: '10001'
                ExtAPIUpdateInvalidEprRegistrationNumberException:
                  value:
                    message: The Germany product EPR registration number is already rejected or deleted, so not able to update.
                    code: '10007'
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to update a Germany product EPR registration number.
      parameters:
      - $ref: '#/components/parameters/de_epr_id'
      tags:
      - Germany EPR Compliance
      summary: Update a Germany Product EPR Registration Number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGermanyProductEprRegistrationNumber'
      security:
      - OAuth2:
        - compliance:write
      operationId: updateGermanyProductEprRegistrationNumber
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\"\n\npayload = \"{\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"{\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"epr_number\":\"string\",\"organization_or_representative_name\":\"string\"}'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"epr_number\\\":\\\"string\\\",\\\"organization_or_representative_name\\\":\\\"string\\\"}\")\n  .asString();"
      description: Update details of a Germany Product EPR Registration Number.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GermanyProductEprRegistrationNumberResponse'
          description: Successfully queried for a Germany product EPR registration number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIEprRegistrationNumberNotFoundException:
                  value:
                    message: The input Germany product EPR registration number is not found by the given id.
                    code: '10003'
                ExtAPIEprRegistrationNumberNoAccessException:
                  value:
                    message: The Germany product EPR registration number is not accessable for the operated merchant.
                    code: '10004'
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to query for a Germany product EPR registration number.
      parameters:
      - $ref: '#/components/parameters/de_epr_id'
      tags:
      - Germany EPR Compliance
      summary: Get a Germany Product EPR Registration Number
      security:
      - OAuth2:
        - compliance:read
      operationId: getGermanyProductEprRegistrationNumber
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      description: Get a Germany product EPR number and product category given its id.
    delete:
      responses:
        '204':
          description: Successfully deleted a Germany product EPR registration number.
        '400':
          content:
            application/json:
              examples:
                ExtAPIEprRegistrationNumberNotFoundException:
                  value:
                    message: The input Germany product EPR registration number is not found by the given id.
                    code: '10003'
                ExtAPIEprRegistrationNumberInvalidFieldException:
                  value:
                    message: The input EPR registration number has invalid fields.
                    code: '10001'
              schema:
                $ref: '#/components/schemas/APIError'
          description: Failed to delete a Germany product EPR registration number.
      parameters:
      - $ref: '#/components/parameters/de_epr_id'
      tags:
      - Germany EPR Compliance
      summary: Delete a Germany Product EPR Registration Number
      security:
      - OAuth2:
        - compliance:write
      operationId: deleteGermanyProductEprRegistrationNumber
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("DELETE", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  \"method\": \"DELETE\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"DELETE\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      - lang: shell_curl
        source: "curl --request DELETE \\\n  --url 'https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.delete(\"https://merchant.wish.com/api/v3/germany_epr_compliance/epr_registration_number/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      description: Delete a Germany Product EPR Registration Number. [This will remove all linked products]
components:
  schemas:
    GermanyProductEprRegistrationNumberResponse:
      description: A Germany product EPR registration number response
      allOf:
      - $ref: '#/components/schemas/GermanyProductEprRegistrationNumber'
      - type: object
        properties:
          id:
            type: string
            description: The unique identifier of a Germany product EPR registration number
            format: object-id
    GermanyEPRComplianceStatus:
      enum:
      - EPR_REGISTRATION_NUMBER_LINKED
      - NO_EPR_REGISTRATION_NUMBER
      - NOT_RECOMMENDED_TO_LINK_EPR_REGISTRATION
      type: string
      description: ' 3 status: (1) an EPR registration number linked, (2) no EPR registration number, (3) not recommended to link an EPR registration.'
    UpdateGermanyProductEprRegistrationNumber:
      type: object
      description: Details of updating a Germany product EPR registration number
      properties:
        epr_number:
          minLength: 1
          type: string
          description: The EPR registration number provided by the merchant
        organization_or_representative_name:
          type: string
          description: The name of the product responsibility organization (PRO) [required for category PACKAGING] or the Authorized Representative (AR) [optional for category ELECTRIC_AND_ELECTRONIC_EQUIPMENTS and BATTERIES]
    GermanyProductComplianceStatus:
      type: object
      properties:
        compliance_status:
          $ref: '#/components/schemas/GermanyEPRComplianceStatus'
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
        epr_registration_number_ids:
          items:
            type: string
            description: The unique identifiers of Germany product EPR registration number
            format: object-id
          type: array
          description: List of unique identifier of EPR registration numbers that are submitted by the merchant for compliance reasons
          maxItems: 500
    GermanyProductEprRegistrationNumber:
      type: object
      description: Details of a Germany product EPR registration number
      properties:
        category:
          enum:
          - BATTERIES
          - ELECTRIC_AND_ELECTRONIC_EQUIPMENTS
          - PACKAGING
          type: string
          description: The enum representing the product category with which the EPR number is associated.
        epr_number:
          minLength: 1
          type: string
          description: The EPR registration number provided by the merchant
        organization_or_representative_name:
          type: string
          description: The name of the product responsibility organization (PRO) [required for category PACKAGING] or the Authorized Representative (AR) [optional for category ELECTRIC_AND_ELECTRONIC_EQUIPMENTS and BATTERIES]
    ListGermanyProductEprRegistrationNumbersResponse:
      items:
        $ref: '#/components/schemas/GermanyProductEprRegistrationNumberResponse'
      type: array
      description: List of Germany Product EPR Registration Numbers returned
    APIError:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
    CreateGermanyProductEprRegistrationNumber:
      type: object
      description: Details of creating a Germany product EPR registration number
      allOf:
      - $ref: '#/components/schemas/GermanyProductEprRegistrationNumber'
      - required:
        - category
        - epr_number
        type: object
    GermanyProductComplianceStatusResponse:
      items:
        $ref: '#/components/schemas/GermanyProductComplianceStatus'
      type: array
      description: List of objects including a product id, compliance status and EPR number id.
    GermanyProductComplianceStatusRequest:
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
        epr_registration_number_id:
          type: string
          description: The unique identifier of an EPR registration number that is submitted by the merchant for compliance reasons
          format: object-id
  parameters:
    de_epr_id:
      schema:
        type: string
        format: object-id
      required: true
      description: The unique identifier of the Germany product EPR registration number
      name: id
      in: path
  securitySchemes:
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://merchant.wish.com/oidc/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            payments:write: Update payments
            tickets:write: Write customer tickets
            epc:read: read EPC info
            returns:write: Write returns
            returns:read: Read returns
            fbw:read: Read FBW
            products:read: Read products
            payments:read: Read payments
            fbw:write: Write FBW
            merchant:write: Write merchant
            products:write: Write products
            ratings:read: Read ratings
            videos:read: Read videos
            compliance:write: Write Compliance
            product_boost:read: Read ProductBoost
            listing_quality:read: Read listing quality
            webhook:write: Write webhook
            orders:read: Read orders
            compliance:read: Read Compliance
            fbs:read: Read FBS
            penalties:read: Read penalties
            penalties:write: Update penalties
            infractions:read: Read infractions
            orders:write: Update orders
            merchant:read: Read merchant
            notifications:write: Write notifications
            announcements:read: Read announcements
            product_boost:write: Write ProductBoost
            notifications:read: Read notifications
            webhook:read: Read webhook
            qoo10:read: Read Qoo10
            wps_parcel:write: Write WishParcel
            wps_parcel:read: Read WishParcel
            tickets:read: Read customer tickets
            infractions:write: Write infractions
            videos:write: Write videos
            epc:write: write EPC info
          tokenUrl: https://merchant.wish.com/api/v3/oauth/access_token
          refreshUrl: https://merchant.wish.com/api/v3/oauth/refresh_token
          authorizationUrl: https://merchant.wish.com/v3/oauth/authorize
externalDocs:
  url: https://merchant.wish.com/documentation/api/v3/explorer
  description: API explorer
x-wish-hidden: false
