openapi: 3.2.0
info:
  contact:
    email: partner-api@wish.com
  x-wish-dev-contact:
    assignee: kwei
    email: marketplace-external-api@contextlogic.com
  description: 'Wish Marketplace V3 API


    # General Information


    The Wish Marketplace API will be using oAuth to authenticate in order to offer better security for its users


    * Learn about oAuth here.'
  version: 3.0.65
  title: Wish Marketplace V3 EU Product Compliance API
servers:
- url: https://merchant.wish.com
  description: V3 API endpoint
security:
- OAuth2: []
tags:
- description: 'APIs that support EU Product Compliance -- EU Regulation 2019/1020 on Market Surveillance and Compliance of Products (MSR).

    For a product to be compliant with the MSR, a product must be linked with a responsible person located in the EU.'
  name: EU Product Compliance
paths:
  /api/v3/eu_product_compliance/responsible_person/{id}:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsiblePersonResponse'
          description: successfully updated a new EU responsible person.
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonInvalidFieldException:
                  value:
                    message: The input responsible person has invalid fields.
                    code: '10001'
                ExtAPIResponsiblePersonNoAccessException:
                  value:
                    message: The responsible person is not accessable for the operated merchant.
                    code: '10004'
                ExtAPIUpdateInvalidResponsiblePersonException:
                  value:
                    message: The responsible person is already rejected or deleted, so not able to update.
                    code: '10007'
                ExtAPIResponsiblePersonNotFoundException:
                  value:
                    message: The input responsible person is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to update a new EU responsible person.
      parameters:
      - $ref: '#/components/parameters/id'
      tags:
      - EU Product Compliance
      summary: Update an EU Responsible Person
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResponsiblePerson'
      security:
      - OAuth2:
        - compliance:write
      operationId: updateEUResponsiblePerson
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\"\n\npayload = \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"address_line1\":\"string\",\"address_line2\":\"string\",\"city\":\"string\",\"country\":\"string\",\"email\":\"string\",\"name\":\"string\",\"phone_number\":\"string\",\"state\":\"string\",\"zipcode\":\"string\"}'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: Update details of an EU Responsible Person.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsiblePersonResponse'
          description: successfully queried for an EU responsible person.
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonNoAccessException:
                  value:
                    message: The responsible person is not accessable for the operated merchant.
                    code: '10004'
                ExtAPIResponsiblePersonNotFoundException:
                  value:
                    message: The input responsible person is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for an EU responsible person.
      parameters:
      - $ref: '#/components/parameters/id'
      tags:
      - EU Product Compliance
      summary: Get an EU Responsible Person
      security:
      - OAuth2:
        - compliance:read
      operationId: getEUResponsiblePerson
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: Get an EU Responsible Person given its id.
    delete:
      responses:
        '204':
          description: successfully deleted an EU responsible person.
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonInvalidFieldException:
                  value:
                    message: The input responsible person has invalid fields.
                    code: '10001'
                ExtAPIDeleteLinkedResponsiblePersonException:
                  value:
                    message: The responsible person is still linked with some products, so not able to delete before unlinking to all related products.
                    code: '10006'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to delete an EU responsible person.
      parameters:
      - $ref: '#/components/parameters/id'
      tags:
      - EU Product Compliance
      summary: Delete an EU Responsible Person
      security:
      - OAuth2:
        - compliance:write
      operationId: deleteEUResponsiblePerson
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("DELETE", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  \"method\": \"DELETE\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.delete(\"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request DELETE \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"DELETE\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: Delete an EU responsible person. Please first call Bulk Update EU Product Compliance Status API to remove all links with products of input responsible person.
  /api/v3/eu_product_compliance/products/bulk_update:
    post:
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkUpdateEUProductComplianceStatusJob'
          description: successfully started a bulk update job.
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonNotFoundException:
                  value:
                    message: The input responsible person is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to start a bulk update job.
      parameters:
      - $ref: '#/components/parameters/old_person_id'
      - $ref: '#/components/parameters/new_person_id'
      tags:
      - EU Product Compliance
      summary: Bulk Update EU Product Compliance Status
      security:
      - OAuth2:
        - compliance:write
      operationId: BulkUpdateProducts
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update"


          querystring = {"old_person_id":"SOME_STRING_VALUE","new_person_id":"SOME_STRING_VALUE"}


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("POST", url, headers=headers, params=querystring)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update?old_person_id=SOME_STRING_VALUE&new_person_id=SOME_STRING_VALUE\",\n  \"method\": \"POST\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.post(\"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update?old_person_id=SOME_STRING_VALUE&new_person_id=SOME_STRING_VALUE\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request POST \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update?old_person_id=SOME_STRING_VALUE&new_person_id=SOME_STRING_VALUE' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update?old_person_id=SOME_STRING_VALUE&new_person_id=SOME_STRING_VALUE\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"POST\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: 'Bulk update links of an EU responsible person with products given a responsible person id.

        Find all products associated with the old responsible person id.

        If new responsible person id is also given, reset above products with new responsible person.

        If no new responsible person id given, unlink above products as no responsible person status.

        This API processes the request asynchronously and triggers a running job.

        Please use Get Bulk Update Job Status API to check the status of a running job'
  /api/v3/eu_product_compliance/products/bulk_update/{id}:
    get:
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkUpdateEUProductComplianceStatusJob'
          description: successfully queried for a bulk update job
        '400':
          content:
            application/json:
              examples:
                ExtAPIBulkRelinkJobNotFoundException:
                  value:
                    message: There is no such bulk update job for the merchant.
                    code: '10008'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for a bulk update job
      parameters:
      - required: true
        in: path
        description: id of the bulk update job to query
        name: id
        schema:
          type: string
          format: object-id
      tags:
      - EU Product Compliance
      summary: Get Bulk Update Job Status
      security:
      - OAuth2:
        - compliance:read
      operationId: GetBulkUpdateStatus
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update/{id}"


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update/{id}\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update/{id}\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update/{id}' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/products/bulk_update/{id}\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: 'Get Status of Bulk Update Job to reset or unlink a responsible person with associated products.

        The job should be triggered by Bulk Update EU Product Compliance Status API'
  /api/v3/eu_product_compliance/products:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EUProductComplianceStatusResponse'
          description: successfully updated EU product compliance status for input products
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to update for EU product compliance status for input products
      tags:
      - EU Product Compliance
      summary: Update EU Product Compliance Status
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/EUProductComplianceStatusRequest'
              type: array
              description: List of a product id associated with update request on EU Product Compliance Status
              maxItems: 500
      security:
      - OAuth2:
        - compliance:write
      operationId: updateEUProductComplianceStatus
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/eu_product_compliance/products\"\n\npayload = \"[{\\\"product_id\\\":\\\"string\\\",\\\"responsible_person_id\\\":\\\"string\\\"}]\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/products\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"[{\\\"product_id\\\":\\\"string\\\",\\\"responsible_person_id\\\":\\\"string\\\"}]\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/eu_product_compliance/products\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"[{\\\"product_id\\\":\\\"string\\\",\\\"responsible_person_id\\\":\\\"string\\\"}]\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/products' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '[{\"product_id\":\"string\",\"responsible_person_id\":\"string\"}]'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/products\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"[{\\\"product_id\\\":\\\"string\\\",\\\"responsible_person_id\\\":\\\"string\\\"}]\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: 'Update the EU product compliance status for each input product by linking with aassociated input responsible_person_id or unlinking the existing responsible person if associated input responsible_person_id is empty or null.

        The input array size limitation is 500.'
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EUProductComplianceStatusResponse'
          description: successfully queried for product compliance status
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonNotFoundException:
                  value:
                    message: The input responsible person is not found by the given id.
                    code: '10003'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for product compliance status
      parameters:
      - $ref: '#/components/parameters/compliance_statuses'
      - $ref: '#/components/parameters/product_ids'
      - required: false
        in: query
        description: The beginning product id(inclusive) of the result array. If not provided, will use the smallest product id.</br> Ignored when product_ids is provided.
        name: product_id_min
        schema:
          type: string
          format: object-id
      - required: false
        in: query
        description: The ending product id(inclusive) of the result array. If not provided, will use the largest product id.</br> Ignored when product_ids is provided.
        name: product_id_max
        schema:
          type: string
          format: object-id
      - in: query
        description: A limit on the number of records that will be returned.</br> Ignored when product_ids is provided.
        name: limit
        schema:
          default: 100
          minimum: 1
          type: integer
          maximum: 500
      - in: query
        description: Sort results by the given attribute. Enabled attributes are `product_id`. Default order is `asc`, use `desc` to sort in reverse.</br> Ignored when product_ids is provided.
        name: sort_by
        schema:
          default: product_id.asc
          pattern: ^product_id(\.(asc|desc))?$
          type: string
      tags:
      - EU Product Compliance
      summary: Get EU Product Compliance Status
      security:
      - OAuth2:
        - compliance:read
      operationId: getEUProductComplianceStatus
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/products"


          querystring = {"compliance_statuses":"SOME_ARRAY_VALUE","product_ids":"SOME_ARRAY_VALUE","product_id_min":"SOME_STRING_VALUE","product_id_max":"SOME_STRING_VALUE","limit":"SOME_INTEGER_VALUE","sort_by":"SOME_STRING_VALUE"}


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers, params=querystring)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/products?compliance_statuses=SOME_ARRAY_VALUE&product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/eu_product_compliance/products?compliance_statuses=SOME_ARRAY_VALUE&product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/products?compliance_statuses=SOME_ARRAY_VALUE&product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/products?compliance_statuses=SOME_ARRAY_VALUE&product_ids=SOME_ARRAY_VALUE&product_id_min=SOME_STRING_VALUE&product_id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: 'Get the EU product compliance status and responsible person id (if linked) for each input product.

        If there is no input product ids, then get the result of all products from a merchant.

        compliance_statuses is an optional input to filter the response.

        The responsible person id will be empty for products not linked with any responsible person.'
  /api/v3/eu_product_compliance/responsible_person:
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsiblePersonResponse'
          description: successfully created a new EU responsible person.
        '400':
          content:
            application/json:
              examples:
                ExtAPIResponsiblePersonInvalidFieldException:
                  value:
                    message: The input responsible person has invalid fields.
                    code: '10001'
                ExtAPIResponsiblePersonExceedLimitException:
                  value:
                    message: The responsible person number exceeds the limit per compliance on the operated merchant.
                    code: '10002'
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to create a new EU responsible person.
      tags:
      - EU Product Compliance
      summary: Create an EU Responsible Person
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResponsiblePerson'
      security:
      - OAuth2:
        - compliance:write
      operationId: createEUResponsiblePerson
      x-code-samples:
      - lang: python_requests
        source: "import requests\n\nurl = \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person\"\n\npayload = \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\"\nheaders = {\n    'content-type': \"application/json\",\n    'authorization': \"Bearer REPLACE_BEARER_TOKEN\"\n    }\n\nresponse = requests.request(\"PUT\", url, data=payload, headers=headers)\n\nprint(response.text)"
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person\",\n  \"method\": \"PUT\",\n  \"headers\": {\n    \"content-type\": \"application/json\",\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  },\n  \"processData\": false,\n  \"data\": \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\"\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.put(\"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person\")\n  .header(\"content-type\", \"application/json\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .body(\"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request PUT \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN' \\\n  --header 'content-type: application/json' \\\n  --data '{\"address_line1\":\"string\",\"address_line2\":\"string\",\"city\":\"string\",\"country\":\"string\",\"email\":\"string\",\"name\":\"string\",\"phone_number\":\"string\",\"state\":\"string\",\"zipcode\":\"string\"}'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"PUT\",\n  CURLOPT_POSTFIELDS => \"{\\\"address_line1\\\":\\\"string\\\",\\\"address_line2\\\":\\\"string\\\",\\\"city\\\":\\\"string\\\",\\\"country\\\":\\\"string\\\",\\\"email\\\":\\\"string\\\",\\\"name\\\":\\\"string\\\",\\\"phone_number\\\":\\\"string\\\",\\\"state\\\":\\\"string\\\",\\\"zipcode\\\":\\\"string\\\"}\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\",\n    \"content-type: application/json\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: Create an EU Responsible Person.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponsiblePersonsResponse'
          description: successfully queried for EU responsible persons.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: failed to query for EU responsible persons.
      parameters:
      - required: false
        in: query
        description: The beginning id(inclusive) of the result array of records. If not provided, will use the smallest responsible person id.
        name: id_min
        schema:
          type: string
          format: object-id
      - required: false
        in: query
        description: The ending id(inclusive) of the result array of records. If not provided, will use the largest responsible person id.
        name: id_max
        schema:
          type: string
          format: object-id
      - in: query
        description: A limit on the number of records that will be returned.
        name: limit
        schema:
          default: 100
          minimum: 1
          type: integer
          maximum: 500
      - in: query
        description: Sort results by the given attribute. Enabled attributes are `id`. Default order is `asc`, use `desc` to sort in reverse.
        name: sort_by
        schema:
          default: id.asc
          pattern: ^id(\.(asc|desc))?$
          type: string
      tags:
      - EU Product Compliance
      summary: List EU Responsible Persons
      security:
      - OAuth2:
        - compliance:read
      operationId: listEUResponsiblePerson
      x-code-samples:
      - lang: python_requests
        source: 'import requests


          url = "https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person"


          querystring = {"id_min":"SOME_STRING_VALUE","id_max":"SOME_STRING_VALUE","limit":"SOME_INTEGER_VALUE","sort_by":"SOME_STRING_VALUE"}


          headers = {''authorization'': ''Bearer REPLACE_BEARER_TOKEN''}


          response = requests.request("GET", url, headers=headers, params=querystring)


          print(response.text)'
      - lang: javascript_jquery
        source: "var settings = {\n  \"async\": true,\n  \"crossDomain\": true,\n  \"url\": \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person?id_min=SOME_STRING_VALUE&id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  \"method\": \"GET\",\n  \"headers\": {\n    \"authorization\": \"Bearer REPLACE_BEARER_TOKEN\"\n  }\n}\n\n$.ajax(settings).done(function (response) {\n  console.log(response);\n});"
      - lang: java_unirest
        source: "HttpResponse<String> response = Unirest.get(\"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person?id_min=SOME_STRING_VALUE&id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\")\n  .header(\"authorization\", \"Bearer REPLACE_BEARER_TOKEN\")\n  .asString();"
      - lang: shell_curl
        source: "curl --request GET \\\n  --url 'https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person?id_min=SOME_STRING_VALUE&id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE' \\\n  --header 'authorization: Bearer REPLACE_BEARER_TOKEN'"
      - lang: php_curl
        source: "<?php\n\n$curl = curl_init();\n\ncurl_setopt_array($curl, array(\n  CURLOPT_URL => \"https://merchant.wish.com/api/v3/eu_product_compliance/responsible_person?id_min=SOME_STRING_VALUE&id_max=SOME_STRING_VALUE&limit=SOME_INTEGER_VALUE&sort_by=SOME_STRING_VALUE\",\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_ENCODING => \"\",\n  CURLOPT_MAXREDIRS => 10,\n  CURLOPT_TIMEOUT => 30,\n  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,\n  CURLOPT_CUSTOMREQUEST => \"GET\",\n  CURLOPT_HTTPHEADER => array(\n    \"authorization: Bearer REPLACE_BEARER_TOKEN\"\n  ),\n));\n\n$response = curl_exec($curl);\n$err = curl_error($curl);\n\ncurl_close($curl);\n\nif ($err) {\n  echo \"cURL Error #:\" . $err;\n} else {\n  echo $response;\n}"
      description: List all EU Responsible Persons created by a merchant.
components:
  parameters:
    product_ids:
      schema:
        items:
          type: string
          description: The unique identifiers of a product
          format: object-id
        type: array
        maxItems: 500
      description: The list of the product IDs that will be returned with the compliance status
      name: product_ids
      in: query
    old_person_id:
      schema:
        type: string
        format: object-id
      required: true
      description: id of the responsible person to unlink for all associated products.
      name: old_person_id
      in: query
    new_person_id:
      schema:
        type: string
        format: object-id
      description: id of the responsible person to update for all associated products of old_person_id.</br> No input (null or empty) means to unlink old_person_id from all its associated products.
      name: new_person_id
      in: query
    compliance_statuses:
      schema:
        minItems: 1
        items:
          $ref: '#/components/schemas/ComplianceStatus'
        type: array
        maxItems: 3
      required: false
      description: '

        Choose the specific compliance status to filter output. Current input values are:


        1. RESPONSIBLE_PERSON_LINKED: a responsible person linked.

        2. NO_RESPONSIBLE_PERSON: no responsible person.

        3. NOT_RECOMMENDED_TO_LINK_RESPONSIBLE_PERSON: not recommended to link a responsible person.

        '
      name: compliance_statuses
      in: query
    id:
      schema:
        type: string
        format: object-id
      required: true
      description: id of the responsible person
      name: id
      in: path
  schemas:
    EUProductComplianceStatusRequest:
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
        responsible_person_id:
          type: string
          description: The unique identifier of a responsible person
          format: object-id
    BulkUpdateEUProductComplianceStatusJob:
      type: object
      properties:
        status:
          enum:
          - PENDING
          - RUNNING
          - COMPLETE
          - EXCEPTION
          type: string
          description: "1. PENDING - The bulk update job has been received and is awaiting processing\n2. RUNNING - The bulk update job is running\n3. COMPLETE -\tThe bulk update job completes successfully\n4. EXCEPTION - The bulk update job aborts with exceptions and please retrigger a new job\n"
        new_person_id:
          type: string
          description: id of the responsible person to update for all associated products of old_person_id.</br> No input (null or empty) means to unlink old_person_id from all its associated products.
          format: object-id
        total_count:
          type: number
          description: Total number of products to update linked responsible person
        created_at:
          type: string
          description: The timestamp on when this job is created
          format: date-time
        updated_at:
          type: string
          description: The timestamp on the latest update of this job
          format: date-time
        processed_count:
          type: number
          description: This number indicates how many products have been processed to update linked responsible person so far
        id:
          type: string
          description: ID of the bulk update job
          format: object-id
        old_person_id:
          type: string
          description: id of the responsible person to unlink for all associated products.
          format: object-id
    ResponsiblePersonResponse:
      description: a responsible person response
      allOf:
      - $ref: '#/components/schemas/ResponsiblePerson'
      - type: object
        properties:
          id:
            type: string
            description: The unique identifier of a responsible person
            format: object-id
    CreateResponsiblePerson:
      type: object
      description: details of creating a responsible person
      allOf:
      - $ref: '#/components/schemas/ResponsiblePerson'
      - required:
        - name
        - address_line1
        - city
        - state
        - zipcode
        - country
        - phone_number
        - email
        type: object
    EUProductComplianceStatusResponse:
      items:
        $ref: '#/components/schemas/EUProductComplianceStatus'
      type: array
      description: List of objects including a product id, compliance status and responsible person id.
    EUProductComplianceStatus:
      type: object
      properties:
        compliance_status:
          $ref: '#/components/schemas/ComplianceStatus'
        product_id:
          type: string
          description: The unique identifier of a product
          format: object-id
        responsible_person_id:
          type: string
          description: The unique identifier of a responsible person
          format: object-id
    ListResponsiblePersonsResponse:
      items:
        $ref: '#/components/schemas/ResponsiblePersonResponse'
      type: array
      description: List of Responsible Persons returned
    ResponsiblePerson:
      type: object
      description: details of a responsible person
      properties:
        address_line2:
          type: string
          description: the address line 2 of the responsible person
        city:
          minLength: 1
          type: string
          description: the city or town of the responsible person
        address_line1:
          minLength: 1
          type: string
          description: the address line 1 of the responsible person
        name:
          minLength: 1
          type: string
          description: name of the responsible person
        country:
          minLength: 1
          type: string
          description: Country code where the responsible person is located
        zipcode:
          minLength: 1
          type: string
          description: the zip code or postal code of the responsible person
        state:
          minLength: 1
          type: string
          description: the state or region of the responsible person
        phone_number:
          minLength: 1
          type: string
          description: the phone number of the responsible person
        email:
          minLength: 1
          type: string
          description: the email of the responsible person
    ComplianceStatus:
      enum:
      - RESPONSIBLE_PERSON_LINKED
      - NO_RESPONSIBLE_PERSON
      - NOT_RECOMMENDED_TO_LINK_RESPONSIBLE_PERSON
      type: string
      description: ' 3 status: (1) a responsible person linked, (2) no responsible person, (3) not recommended to link a responsible person.'
    APIError:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
  securitySchemes:
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://merchant.wish.com/oidc/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            payments:write: Update payments
            tickets:write: Write customer tickets
            epc:read: read EPC info
            returns:write: Write returns
            returns:read: Read returns
            fbw:read: Read FBW
            products:read: Read products
            payments:read: Read payments
            fbw:write: Write FBW
            merchant:write: Write merchant
            products:write: Write products
            ratings:read: Read ratings
            videos:read: Read videos
            compliance:write: Write Compliance
            product_boost:read: Read ProductBoost
            listing_quality:read: Read listing quality
            webhook:write: Write webhook
            orders:read: Read orders
            compliance:read: Read Compliance
            fbs:read: Read FBS
            penalties:read: Read penalties
            penalties:write: Update penalties
            infractions:read: Read infractions
            orders:write: Update orders
            merchant:read: Read merchant
            notifications:write: Write notifications
            announcements:read: Read announcements
            product_boost:write: Write ProductBoost
            notifications:read: Read notifications
            webhook:read: Read webhook
            qoo10:read: Read Qoo10
            wps_parcel:write: Write WishParcel
            wps_parcel:read: Read WishParcel
            tickets:read: Read customer tickets
            infractions:write: Write infractions
            videos:write: Write videos
            epc:write: write EPC info
          tokenUrl: https://merchant.wish.com/api/v3/oauth/access_token
          refreshUrl: https://merchant.wish.com/api/v3/oauth/refresh_token
          authorizationUrl: https://merchant.wish.com/v3/oauth/authorize
externalDocs:
  url: https://merchant.wish.com/documentation/api/v3/explorer
  description: API explorer
x-wish-hidden: false
